import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import PrelineScript from "./components/PrelineScript";
import './globals.css'
import ConfigureAmplifyClientSide from './components/ConfigureAmplify';
import '@aws-amplify/ui-react/styles.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const amplifyTheme = {
  name: 'custom-theme',
  tokens: {
    colors: {
      primary: {
        10: 'grey',
        20: 'grey',
        30: 'grey',
        40: 'black',
        50: 'black',
        60: 'black',
        70: 'black',
        80: 'black',
        90: 'black',
      },
    },
  }
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <ConfigureAmplifyClientSide />
            {children}
          <PrelineScript/>
      </body>
    </html>
  )
}